force-app/main/default/objects/Candidato__c/Candidato__c.object-meta.xml
<CustomObject>
    <description>Um candidato é uma pessoa que foi convidada para participar dos jogos mas ainda não aceitou.</description>
    <label>Candidato</label>
    <nameField>
        <label>Nome do Candidato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidato__c/fields/CEPAlterado__c.field-meta.xml
<CustomField>
    <fullName>CEPalterado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CEP alterado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot;Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status do round</description>
    <inlineHelpText>Status do round</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Definição</fullName>
                <default>true</default>
                <label>Em Definição</label>
            </value>
            <value>
                <fullName>Coletando Candidatos</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Coletando Candidato</fullName>
                <isActive>false</isActive>
                <label>Coletando Candidato</label>
            </value>
            <value>
                <fullName>jujuba</fullName>
                <isActive>false</isActive>
                <label>jujuba</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MapsFields.cls
public with sharing class MapsFields {
        private String query;

        Map<Schema.SObjectField, Object> fieldsValuesMap = new Map<Schema.SObjectField, Object> ();
               
        String e = 'Lead'; // Object to be updated
	    String f = 'LeadSource'; // field to be updated.
	    String v = 'DarkWeb'; // value with which field will be populated.
	    String q = 'SELECT ' + f + ' FROM ' + e; // Query to which more filters can be added like: + 'AND IsConverted = false';
	    


    //    Database.executeBatch(new UpdateFieldsBatchable(query,null));
            


       // Map<Schema.SObjectField, Object> fieldsValuesMap = new Map<Schema.SObjectField, Object> {
       //     Candidato__c.CEPAlterado__c => false,
       //     Candidato__c.DataUltimaBatch__c => System.today()
      //  };

       // Map<Schema.SObjectField, Object> fieldsValuesMap = new Map<Schema.SObjectField, Object> {
       //     Round__c.Status__c => 'Finalizado',
       //     Candidato__c.Name => 'soifjf'
       // };

      // Database.executeBatch(new UpdateFieldsBatchable(null,null));
}