force-app/main/default/objects/Candidato__c/Candidato__c.object-meta.xml
<CustomObject>
    <description>Um candidato é uma pessoa que foi convidada para participar dos jogos mas ainda não aceitou.</description>
    <label>Candidato</label>
    <nameField>
        <label>Nome do Candidato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidato__c/fields/CEPAlterado__c.field-meta.xml
<CustomField>
    <fullName>CEPalterado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CEP alterado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CandidatosCEPAlteradosBatchable.cls
public with sharing class CandidatosCEPAlteradosBatchable implements Database.Batchable<SObject> {
    
    String query;

    public Database.QueryLocator start(Database.BatchableContext BC){
        //return Database.getQueryLocator(CandidatoSelector.getQueryLocatorCEPBatchable());
        System.debug('Entrou no start');
        return Database.getQueryLocator(CandidatoSelector.getQueryLocatorCEPBatchable());
    }
    public void execute(Database.BatchableContext BC, List<Candidato__c> scope){
        System.debug('Vai executar');
        for (Candidato__c record : scope){
          // record.CEPAlterado__c = false;
         //  error += record.Id + ' - ';
          System.debug('Record: '+record.Name);
       }     
    } 

    public void finish(Database.BatchableContext BC){
        //System.debug('error: '+ error);
         System.debug('Acabou');
    }
}