force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{00000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ETHO-5/Etho-5/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado para informar se o jogado foi eliminado</description>
    <inlineHelpText>Jogado foi eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

ETHO-5/Etho-5/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Usado para informar o joso em que o participante jogou</description>
    <inlineHelpText>Usado para informar o joso em que o participante jogou</inlineHelpText>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot;Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status do round</description>
    <inlineHelpText>Status do round</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Definição</fullName>
                <default>true</default>
                <label>Em Definição</label>
            </value>
            <value>
                <fullName>Coletando Candidatos</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Coletando Candidato</fullName>
                <isActive>false</isActive>
                <label>Coletando Candidato</label>
            </value>
            <value>
                <fullName>jujuba</fullName>
                <isActive>false</isActive>
                <label>jujuba</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StatusRoundSelector.cls
public with sharing class StatusRoundSelector {
    public static List<Round__c> selectByRoundsIdsWithJogadores(Set<Id> ids) {
        return [
              SELECT (SELECT Id,Velocidade__c , Forca__c, Inteligencia__c  
                        FROM Jogadores__r 
                       WHERE Eliminado__c = false)
                FROM Round__c 
               WHERE Status__c IN :ids
        ];
    }
}