force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{00000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ETHO-5/Etho-5/force-app/main/default/objects/Jogador__c/fields/Data_da_Morte__c.field-meta.xml
<CustomField>
    <fullName>Data_da_Morte__c</fullName>
    <description>Usado para a data da morte</description>
    <inlineHelpText>Data da morte do jogados</inlineHelpText>
    <label>Data da Morte</label>
    <type>DateTime</type>
</CustomField>

ETHO-5/Etho-5/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado para informar se o jogado foi eliminado</description>
    <inlineHelpText>Jogado foi eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

ETHO-5/Etho-5/force-app/main/default/classes/JogadoresTriggerHandler.cls
public without sharing class JogadoresTriggerHandler {
    public static void beforeUpdate(List<jogador__c>  records, Map<id, jogador__c> oldMap){
          for (Jogador__c jogador :records){//realiza uma iteração
                beforeUpdate(jogador,oldMap.get(jogador.id));         
          }
    }

    private static void beforeUpdate(Jogador__c record,Jogador__c recordOld){
        if(isChanged(recordOld.Eliminado__c,record.Eliminado__c)){
            record.Data_da_Morte__c = System.now();//atribuição
        }        
    }

    private static Boolean isChanged(Boolean value, Boolean valueToCompare){
        return value != valueToCompare;
    }
}