force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{00000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ETHO-5/Etho-5/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado para informar se o jogado foi eliminado</description>
    <inlineHelpText>Jogado foi eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

ETHO-5/Etho-5/force-app/main/default/objects/ParticipantesPartida__c/ParticipantesPartida__c.object-meta.xml
<CustomObject>
    <description>Tabela de ligação de Jogadores da partida</description>
    <label>Participante da Partida</label>
    <nameField>
        <displayFormat>Par-{000000}</displayFormat>
        <label>Número do Participante da Partida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes da Partidas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipantesPartida__c/fields/Jogador__c.field-meta.xml
<CustomField>
    <fullName>Jogador__c</fullName>
    <description>Jogador da Partida</description>
    <inlineHelpText>Jogador da Partida</inlineHelpText>
    <label>Jogador</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipName>Participantes_da_Partidas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ETHO-5/Etho-5/force-app/main/default/objects/ParticipantesPartida__c/fields/Partida__c.field-meta.xml
<CustomField>
    <fullName>Partida__c</fullName>
    <description>Partida que o jogador participou</description>
    <inlineHelpText>Partida que o jogador participou</inlineHelpText>
    <label>Partida</label>
    <referenceTo>Partida__c</referenceTo>
    <relationshipName>ParticipantesPartidas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ETHO-5/Etho-5/force-app/main/default/objects/Partida__c/Partida__c.object-meta.xml
<CustomObject>
    <description>Jogo de cada round</description>
    <label>Partida</label>
    <nameField>
        <label>Nome de Partida</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partidas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ETHO-5/Etho-5/force-app/main/default/objects/Partida__c/fields/TerminoPartida__c.field-meta.xml
<CustomField>
    <fullName>TerminoPartida__c</fullName>
    <description>Data do término da partida</description>
    <inlineHelpText>Data do término da partida</inlineHelpText>
    <label>Témino da Partida</label>
    <type>DateTime</type>
</CustomField>

ETHO-5/Etho-5/force-app/main/default/classes/BatatinhaFrita.cls
public class BatatinhaFrita {
           public void execute (Id idPartida)
           {
               ParticipantesPartida__c[] participantes = [SELECT Id, Jogador__c FROM ParticipantesPartida__c WHERE Partida__c = :idPartida];
               System.debug(participantes);
               Jogador__c[] jogadores = new List<Jogador__c>();
               Integer mortes = (Integer) participantes.size() / 2;
               
               for(Integer i = 0; i < mortes; i++)
               {
                   Jogador__c jogador = new Jogador__c();
                   jogador.Id = participantes[i].Jogador__c;
                   jogador.Eliminado__c = true;
                   jogadores.add(jogador);
               }
               
               /*update jogadores;
               
               update new Partida__c(Id = idPartida, TerminoPartida__c = System.now());*/
           
           }
}