force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{00000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ETHO-5/Etho-5/force-app/main/default/objects/Jogador__c/fields/Morreu__c.field-meta.xml
<CustomField>
    <fullName>Morreu__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controla a morte dos jogadores</description>
    <label>Morreu</label>
    <type>Checkbox</type>
</CustomField>

ETHO-5/Etho-5/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Usado para informar o joso em que o participante jogou</description>
    <inlineHelpText>Usado para informar o joso em que o participante jogou</inlineHelpText>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot;Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AssassinatosHandler.cls
public with sharing class AssassinatosHandler {
      
    public static void execute(){  
      List<Round__c> records = StatusRoundSelector.selectByRoundsIdsWithJogadores('Andamento');
  
      for (Round__c record : records) {
            handleAssassinato(record);
      } 
    }
   
    private static void randomAssassinato(Round__c record) {
      Lit<Jogador__c> jogadores = round.Jogadores__r;
      Integer qtdJogadoresVivos = jogadores.size();

      if (qtdJogadoresVivos >1)
      {
         jogador__c atacante = Utils.generateRandomIntegerBetween(qtdJogadoresVivos,qtdJogadoresVivos-1);
         jogador__c defensor = Utils.generateRandomIntegerBetween(qtdJogadoresVivos,qtdJogadoresVivos-1);
         
         handleAtributo(atacante,defensor,qtdJogadoresVivos) ;
         handleAssassinato(atacante,defesa,qtdJogadoresVivos); 
      }
    }
    
    private static void handleAssassinato(Jogador__c atacante, Jogador__c defensor, Lit<Jogador__c> qtdJogadoresVivos) {
              
        if (ataque > defesa) {
            setValue(defesa, Jogador__c.Morreu__c, true);
        } else{
                if (ataque < defesa) && (dadoAtacante = 1){
                     handleAtributo(defensor,atacante,qtdJogadoresVivos) ;
                }
        } 
        setValue(atacante, Jogador__c.Morreu__c, true);
        }       
    }

    private static void handleAtributo(Integer ataque, Integer defesa, Integer qtdJogadoresVivos) {
        Integer dadoAtacante = Utils.generateRandomIntegerBetween(qtdJogadoresVivos,-1);
        Integer ataque = dadoAtacante + atacante.Forca__c;
        Integer defesa = Utils.generateRandomIntegerBetween(qtdJogadoresVivos,-1)+
                         Utils.generateRandomIntegerBetween(qtdJogadoresVivos,+1)+
                         defensor.Inteligencia__c+defensor.Velocidade__c;          
        handleAssassinato(atacante,  defensor);                  
    } 
}    