force-app/main/default/objects/Assassinato__c/Assassinato__c.object-meta.xml
<CustomObject>
    <label>Assassinato</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número do assassinato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assassinatos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assassinato__c/fields/Assassinado__c.field-meta.xml
<CustomField>
    <fullName>Assassinado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assassinado</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Assassinatos (Assassinado)</relationshipLabel>
    <relationshipName>Assassinados2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{00000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ETHO-5/Etho-5/force-app/main/default/objects/Jogador__c/fields/Morreu__c.field-meta.xml
<CustomField>
    <fullName>Morreu__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controla a morte dos jogadores</description>
    <label>Morreu</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AssassinatosTriggerHandler.cls
public without sharing class AssassinatosTriggerHandler {

    public static void afterInsert(List<Assassinato__c> records) {
        List<Jogador__c> jogadoresMortos = new List<Jogador__c>();
        for (Assassinato__c record : records) {
            mataJogadorAssassinado(record, jogadoresMortos);
        }
        update jogadoresMortos;
    }

    //TODO: 
    static void mataJogadorAssassinado(Assassinato__c record, List<Jogador__c> jogadoresMortos) {
        jogadoresMortos.add(
            new Jogador__c(
                Id = record.Assassinado__c,
                Morreu__c = true
            )
        );
    }
}